speasy/amda/amda.py
tests/test_amda_parameter.py

- Since we added new inventory entries there could be some code path where inventory was cached but with missing entries.
- Given a time range a downloaded parameter won't match exactly start time and end time but should contain the first data at or after start time to the last data before stop time.

Fixes few minor issues in AMDA module

---

speasy/webservices/amda/utils.py
tests/test_amda.py

Small fix for downloading multidimensional data from AMDA

fixed amda multidimensional data download, column names

---

.github/workflows/PRs.yml
.github/workflows/tests.yml

While releasing 0.10.0, I discovered that I broke title consistency between README and HISTORY which are used for generating PyPi landing page.
To avoid this, I propose to generate python packages on each push and PR and just run `twine check` to ensure everything still works.

[CI] Check that each push or PR doesn't break release process

---

speasy/products/catalog.py
speasy/products/timetable.py
speasy/webservices/amda/ws.py
tests/test_amda_catalog.py
tests/test_amda_timetable.py
tests/test_spwc.py

This does a simple conversion to Pandas DataFrames for TT and Catalogs. Note that Catalogs as defined in Speasy doesn't force Events to always have the same meta-data, this leads to a DataFrame where columns are the union of all Events meta-data plus as usual start_time and stop_time.
Closes #35

Adds TimeTable and Catalog conversion to Pandas DataFrames

---

.github/workflows/PRs.yml
.github/workflows/tests.yml
docs/conf.py
speasy/config/__init__.py
speasy/webservices/amda/_impl.py
speasy/webservices/amda/rest_client.py
tests/test_amda.py

Added process status management for AMDA requests
Split time range by days.

added time range splitting and process status management

---

.github/workflows/PRs.yml
.github/workflows/tests.yml
speasy/core/__init__.py
speasy/webservices/cda/_inventory_builder/_xml_catalogs_parser.py
tests/test_speasy.py

It seems that some instruments nodes names are empty so just skip them and just directly add datasets nodes into parent node.
It might not be enough to cover all cases, a more systematic analysis might be required to spot all "broken nodes".

Forces inventory build tests on CI and fixes a bug with CDA inventory

---

speasy/config/__init__.py
speasy/core/requests_scheduling/request_dispatch.py
tests/test_disable_ws.py
tests/test_speasy.py
tests/test_zzz_disable_ws.py

This adds an undocumented option to disable any web-service support in speasy. 
As discussed in meeting, this will speedup speasy loading for use-cases where only one web-service is used.

Adds option to disable webservices, closes #64

---

speasy/core/cache/_providers_caches.py
speasy/core/data_containers.py
tests/test_cdaweb.py

This PR covers both issues described in #75 , first when we fail to load a cache fragment, we just continue and get corresponding data as if it never was in cache. Then there was an assumption that all axes values were numerical, let's just support the case where we can also get pure text in axes data.

Fix bug #75

---

speasy/core/cdf/__init__.py
tests/test_cdaweb.py

Products like ERG_ORBS_L3/pos_eq_op from CDAWeb miss LABEL_PTR_1 attribute, this PR will generate some depending on what's available.
This only applies to multi components time-series.

Handles cases where labels are missing in CDAWeb generated files

---

speasy/webservices/amda/_impl.py
speasy/webservices/amda/utils.py
tests/resources/derived_param.txt
tests/resources/derived_param2.txt
tests/test_amda.py

Since CSV is still the default format for ADMA with speasy, I felt like we should fix this issue.

Fixes AMDA CSV parser where derived parameters attributes gets overwritten by base param

---

speasy/core/cdf/__init__.py
speasy/webservices/generic_archive/__init__.py
tests/test_direct_archive_downloader.py

Some files uses DEPEND_TIME instead of DEPEND_0 to point to time axis. This was supported by speasy for data variables but not for support variables.

Fixes non ISTP compliant files axis merging

---

.github/ISSUE_TEMPLATE.md
scripts/direct_archive_yaml_gen.ipynb
speasy/core/direct_archive_downloader/direct_archive_downloader.py
speasy/data/archive/cda.yaml
tests/test_direct_archive_downloader.py

There is not always a file for a given time interval on remote servers, so speasy should handle this and just return None 
instead of crashing.
This PR also adds few more products from CDAWeb archive access for MMS as examples and useful to test this PR.

Fix archive no files

---

speasy/core/http.py
speasy/core/proxy/__init__.py
speasy/core/requests_scheduling/request_dispatch.py
speasy/core/url_utils.py
speasy/webservices/amda/_impl.py
speasy/webservices/amda/rest_client.py
speasy/webservices/amda/ws.py
speasy/webservices/cda/__init__.py
speasy/webservices/csa/__init__.py
speasy/webservices/generic_archive/__init__.py
speasy/webservices/ssc/__init__.py
tests/test_http_module.py
tests/test_url_utils.py

This PR is a proposition to keep speasy usable if any server/WS is down only losing associated features.

Tentative to survive to servers outage by simply disabling Ws when servers are down

---

speasy/core/cdf/__init__.py

The current code works but generates a warning and will generate an error in the future.

Fixes regex \ escaping warning

---

docs/user/amda/amda.rst
speasy/core/__init__.py
speasy/core/cache/_providers_caches.py
tests/test_amda_parameter.py
tests/test_http_module.py

This was a long standing bug I mainly see on our proxy but didn't understand until now. 
In the maybe outdated section I can still get a None entry value.

If last cache fragment is None then don't slice it

---

.github/workflows/PRs.yml
.github/workflows/tests.yml
speasy/config/__init__.py
speasy/core/any_files.py
speasy/core/http.py
speasy/core/url_utils.py
tests/test_file_access.py

This will allow to replace cdaweb URL with our nginx reverse proxy set up with proxy_cache module from speasy_proxy module.

New basic rewrite rule for http module, mostly for internal uses

---

docs/user/csa/csa.rst
speasy/config/__init__.py
speasy/webservices/cda/__init__.py

Using proxy here would mean adding another cache level, just use our cdaweb cached reverse proxy instead.

Using SciQLop proxy for CDA direct files access makes no sense

---

pyproject.toml
speasy/products/variable.py
tests/test_speasy_variable.py

Some Numpy functions like sum, mean,... reduces the number of dimensions so resulting SpeasyVariables must adjust axes accordingly.

Reduces axes count according to numpy reduction

---

docs/user/direct_archive/direct_archive.rst
speasy/core/direct_archive_downloader/direct_archive_downloader.py
speasy/products/catalog.py
tests/test_direct_archive_downloader.py

This can be used as a workaround for non ISTP compliant CDFs or others unsupported formats.

Allows to pass a custom file reader to the archive module

---

.coveragerc
.github/workflows/PRs.yml
.github/workflows/tests.yml
requirements_dev.txt
speasy/core/any_files.py
speasy/core/direct_archive_downloader/direct_archive_downloader.py
tests/test_direct_archive_downloader.py
tests/test_file_access.py

When downloading remote files a temporary cache entry is created to notify any concurrent request on the same file.
This ensures we only download once any file when requesting it from several concurrent processes or threads.
Another improvement it brings, is download sequence randomization when the archive module need to merge several files, since with deduplication any concurrent process will sleep/wait until the data is there, reducing chances of collisions increases chances that all processes are requesting a different file at the same time. 
It improves a lot the use case when the user want to plot in SciQLop several products from the same dataset across several days or files. (each file is downloaded once and, its likely that thanks to randomization not all threads will request the …

Adds request deduplication for cached remote file access

---

speasy/core/cache/cache.py
speasy/core/data_containers.py
speasy/core/proxy/__init__.py
tests/test_speasy_variable.py

To avoid any weirdness with cache and proxy, I increased the cache model version which triggers a cache flush and minimum proxy version.
closes #139.

Preserves SpeasyVariable values dtype across dictionary serialization

---

speasy/core/__init__.py
speasy/webservices/cda/_inventory_builder/__init__.py

Previous mkdir would sometimes err in multithread-python , see discussion
https://stackoverflow.com/questions/42544885/error-when-mkdir-in-multi-threads-in-python

fix: allow mkdir work in multi threads in python

---

pyproject.toml
requirements.txt
requirements_dev.txt
speasy/core/cdf/inventory_extractor.py
speasy/webservices/cda/_inventory_builder/_cdf_masters_parser.py
tests/test_direct_archive_downloader.py

Extract more information from CDF while building the inventory

---

pyproject.toml
speasy/core/cache/__init__.py
speasy/core/codecs/bundled_codecs/istp_cdf.py
tests/test_cdaweb.py
tests/test_common.py

In some cases for 2D DATA CDFs, the 2nd axis has a DEPEND0 while it also is Non Record Vary. Speasy has to consider that those axes are not time dependent.

Fixes #169, and adds functions to drop cache entries matching regex.

---

speasy/core/data_containers.py
speasy/products/variable.py
tests/test_speasy_variable.py

Valid min and valid max

---

speasy/core/requests_scheduling/request_dispatch.py

Added a force parameter to each of the initialization functions.
This parameter allows you to force the initialization of providers even if disabled by config (init_amda, init_csa, init_cdaweb, init_sscweb, and init_archive).

Force init

---

speasy/core/impex/__init__.py
speasy/core/inventory/indexes.py
speasy/core/proxy/__init__.py
speasy/data_providers/cda/_inventory_builder/__init__.py
speasy/data_providers/csa/__init__.py
tests/test_inventories.py

This pull request includes several changes to improve inventory management and proxy version handling, as well as the addition of new tests. The most important changes include the introduction of versioning in `to_dict` and `from_dict` functions, updates to the proxy version, and the addition of utility functions to handle primitive types.
* [`speasy/core/inventory/indexes.py`](diffhunk://#diff-0aa4d4fe160642c4c462c689d7af654952247fe0096b3cd070ca98a9bc505efdL148-R193): Added a `version` parameter to the `to_dict`, `from_dict`, `to_json`, and `from_json` functions to support different versions of inventory serialization. [[1]](diffhunk://#diff-0aa4d4fe160642c4c462c689d7af654952247fe0096b3cd070ca98a9bc505efdL148-R193) [[2]](diffhunk://#diff-0aa4d4fe160642c4c462c689d7af654952247fe0096b3cd070c …

Introduce a new inventory JSON/dict format that preserves more primitive types

---

speasy/data_providers/amda/ws.py

This pull request includes a change to the `speasy/data_providers/amda/ws.py` file to update the handling of proxy parameters. The most important change involves modifying the conditional check and key used for additional arguments.
Changes to proxy parameter handling:
* [`speasy/data_providers/amda/ws.py`](diffhunk://#diff-7fb717891684e55d92ba40db546e15f4c678df3dfc9fddeca532898fca88c5c9L117-R118): Updated the conditional check from `additional_arguments` to `product_inputs` and changed the key in the `proxy_args` dictionary accordingly.

Quick fix for leftover additional_argument instead of product_inputs

---

speasy/core/codecs/bundled_codecs/istp_cdf.py
speasy/core/data_containers.py
tests/test_cdaweb.py
tests/test_codecs.py

This pull request includes several changes to the `speasy/core/codecs/bundled_codecs/istp_cdf.py` file, improvements to the `speasy/core/data_containers.py` file, and additional tests in the `tests/test_cdaweb.py` and `tests/test_codecs.py` files. The most important changes include adding new functions, modifying existing functions to handle specific conditions, and adding new test cases to ensure the robustness of the code.
* Added import for `SupportDataVariable` from `pyistp.support_data_variable`.
* Introduced `_display_type` function to handle display type attributes in `DataVariable`.
* Added `_filter_extra_axes` function to filter out extra axes from `DataVariable`.
* Added `_valid_variable_or_none` function to handle fill values in epoch.
* Modified `_load_variable` function to …

Handles corner cases with Cluster CDF files

---

speasy/core/__init__.py
speasy/data_providers/cda/_inventory_builder/_cdf_masters_parser.py
tests/test_cdaweb.py

This pull request includes several changes to improve the handling of names with special characters and to enhance the test coverage for the `speasy` package. The most important changes include the addition of a new character replacement in the `fix_name` function, the integration of this function into the `_cdf_masters_parser`, and the introduction of a utility function to reset cache flags in tests.
* [`speasy/core/__init__.py`](diffhunk://#diff-2ea3f222debe7d37c3203de600be333ce5d09ff853a18409fe985509d73d4ae1L325-R326): Added a replacement for the '%' character with an underscore in the `fix_name` function.
* [`speasy/data_providers/cda/_inventory_builder/_cdf_masters_parser.py`](diffhunk://#diff-6c47903d6b33858f327b06987521b4c829684220cf999ccb3698ff9929a2d016L22-R23): Integrated the …

CDAWeb inventory product node names were not cleanned

---

docs/user/sscweb/sscweb.rst
tests/test_direct_archive_downloader.py

This pull request updates the test cases in `tests/test_direct_archive_downloader.py` to reflect a version change in the URL patterns for the `erg_pwe_hfa_l3_1min` dataset. The version has been incremented from `v04_08` to `v04_09`.
* Updated the URL pattern in `test_unknown_split_rules_raises` to use `v04_09` instead of `v04_08`.
* Updated the URL patterns in `test_download_existing_data` to reflect the version change from `v04_08` to `v04_09`.

Fixes CI issues on #215 and #216

---

speasy/products/variable.py
tests/test_speasy_variable.py

This pull request refactors the `sanitized` method in `speasy/products/variable.py` to improve clarity and efficiency, removes the `inplace` parameter, and updates the corresponding tests to ensure robustness. The most important changes are summarized below:
* Removed the `inplace` parameter from the `sanitized` method, simplifying its functionality to always return a new filtered copy of the variable. [[1]](diffhunk://#diff-85f04bb7467121cc0c8346b1abcfc51def0e90587138125e1e50f9953f6690f4L761-R762) [[2]](diffhunk://#diff-85f04bb7467121cc0c8346b1abcfc51def0e90587138125e1e50f9953f6690f4L773-L774)
* Refactored the filtering logic in the `sanitized` method to use a list of conditions (`indexes`) and `np.logical_and.reduce`, improving code readability and efficiency.
* Added a validation step …

Fixes #214

---

.github/workflows/tests.yml
tests/test_http_module.py

This pull request updates the `test_basic_http_auth` method in `tests/test_http_module.py` to handle cases where a `.netrc` file is missing. The change ensures the test is skipped gracefully if the file is not found.
* **Improved test robustness:**
* Added a `try-except` block to handle `FileNotFoundError` when attempting to load the `.netrc` file. If the file is not found, the test is skipped with an appropriate message. (`[tests/test_http_module.pyR34-R40](diffhunk://#diff-7c47365ed30bf8b20ad8a1b1b40c08b09f0cc8db176358054297941fe5771a52R34-R40)`)

Skip auth http test also if there is no netrc file and bi-weekly CI run

---

speasy/core/requests_scheduling/request_dispatch.py
tests/test_speasy.py

This pull request introduces a small update to the provider registration logic in the `init_uiowaephtool` function. The change ensures that the `UiowaEphTool` provider is registered under both the lowercase and camel-case keys in the `PROVIDERS` dictionary, improving consistency and compatibility.
* Registration update:
* [`speasy/core/requests_scheduling/request_dispatch.py`](diffhunk://#diff-5aa38a31965b762909190b5464c52b1f5134f217804442f2b7e5f206fe25d85dR99): Added `PROVIDERS['UiowaEphTool'] = uiowaephtool` to register the provider under both possible key formats.

[UiowaEphTool] products are registered with UiowaEphTool as provider
